### ISSUE TITLE
h5tojson fails to convert TES-Aura_L2-O3-Nadir_r0000011015_F05_07.he5.

### ISSUE THREAD

**Issue by hyoklee** [HDFGroup/hdf5-json#19]
The test file is at ftp://ftp.hdfgroup.uiuc.edu/pub/outgoing/NASAHDF/TES-Aura_L2-O3-Nadir_r0000011015_F05_07.he5

```
Traceback (most recent call last):
  File "h5tojson.py", line 232, in <module>
    main()
  File "h5tojson.py", line 229, in main
    dumper.dumpFile()    
  File "h5tojson.py", line 184, in dumpFile
    self.dumpDatasets()
  File "h5tojson.py", line 146, in dumpDatasets
    item = self.dumpDataset(uuid)
  File "h5tojson.py", line 135, in dumpDataset
    value = self.db.getDatasetValuesByUuid(uuid)
  File "../lib/hdf5db.py", line 1715, in getDatasetValuesByUuid
    values = dset[slices].tolist()  # just dump to list
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/tmp/pip_build_root/h5py/h5py/_objects.c:2405)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/tmp/pip_build_root/h5py/h5py/_objects.c:2362)
  File "/usr/local/lib/python2.7/site-packages/h5py/_hl/dataset.py", line 467, in __getitem__
    self.id.read(mspace, fspace, arr, mtype)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/tmp/pip_build_root/h5py/h5py/_objects.c:2405)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/tmp/pip_build_root/h5py/h5py/_objects.c:2362)
  File "h5py/h5d.pyx", line 175, in h5py.h5d.DatasetID.read (/tmp/pip_build_root/h5py/h5py/h5d.c:3004)
  File "h5py/_proxy.pyx", line 150, in h5py._proxy.dset_rw (/tmp/pip_build_root/h5py/h5py/_proxy.c:1777)
  File "h5py/_proxy.pyx", line 319, in h5py._proxy.needs_bkg_buffer (/tmp/pip_build_root/h5py/h5py/_proxy.c:3304)
  File "h5py/_proxy.pyx", line 316, in h5py._proxy.needs_bkg_buffer (/tmp/pip_build_root/h5py/h5py/_proxy.c:3243)
KeyError: 'Conversion function not found (No appropriate function for conversion path)'
```

**Comment by jreadey** [comment]
I created a smaller test file that repos the issue:   hdf5-json/data/hdf5/vlen_string_dset_utc.h5

Uncomment the last line of testReadVlenStringDataset_utc to trigger the error.

Issue is opened in h5py: https://github.com/h5py/h5py/issues/565.

**Comment by ajelenak** [comment]
The `vlen_string_dset_utc.h5` test case works  with the latest h5json master branch and h5py 3.3.0.
