### ISSUE TITLE
Error after switching to Apple M1

### ISSUE THREAD

**Issue by dcu** [HDFGroup/hdf5-json#70]
hello,

I just switched to M1 and h5tojson stopped working with an unknown error:

```
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniconda/base/bin/h5tojson", line 8, in <module>
    sys.exit(main())
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.8/site-packages/h5json/h5tojson/h5tojson.py", line 244, in main
    dumper.dumpFile()
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.8/site-packages/h5json/h5tojson/h5tojson.py", line 198, in dumpFile
    self.dumpGroups()
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.8/site-packages/h5json/h5tojson/h5tojson.py", line 105, in dumpGroups
    item = self.dumpGroup(uuid)
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.8/site-packages/h5json/h5tojson/h5tojson.py", line 90, in dumpGroup
    attributes = self.dumpAttributes('groups', uuid)
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.8/site-packages/h5json/h5tojson/h5tojson.py", line 55, in dumpAttributes
    attr_list = self.db.getAttributeItems(col_name, uuid)
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.8/site-packages/h5json/hdf5db.py", line 1226, in getAttributeItems
    item = self.getAttributeItemByObj(obj, name, False)
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.8/site-packages/h5json/hdf5db.py", line 1176, in getAttributeItemByObj
    shape_json = self.getShapeItemByAttrObj(attrObj)
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.8/site-packages/h5json/hdf5db.py", line 853, in getShapeItemByAttrObj
    if obj.shape is None or obj.get_storage_size() == 0:
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5a.pyx", line 443, in h5py.h5a.AttrID.get_storage_size
  File "h5py/defs.pyx", line 353, in h5py.defs.H5Aget_storage_size
RuntimeError: Unspecified error in H5Aget_storage_size (return value ==0)
```

I'm not sure if this is related to the switch to M1 or something else but it used to work in my old laptop.
I'd be great if someone can report back your results when using M1

**Comment by ajelenak** [comment]
@dcu Is this still failing?

**Comment by ajelenak** [comment]
Closing as inactive.
